### ISSUE TITLE
Choosing video type for an input

### ISSUE THREAD

**Issue by bananenbuurman** [bitfocus/companion-module-kramer-vp727#1]
I would like to use companion to set the video Type (Composite, Y/C, Component, HDMI, etc.) 

I have added this functionality to index.js attached as index.txt

You can set a different videotype per input. When you change videotype it happens to the currently selected input. 

As this needs to be compiled I was unable to test this.
[index.txt](https://github.com/bitfocus/companion-module-kramer-vp727/files/8460146/index.txt)

**Comment by josephdadams** [comment]
@bananenbuurman I encourage you to take the extra step to learn how to submit a pull request for this if you would like it to be added. Otherwise I doubt this will ever get implemented.

**Comment by bananenbuurman** [comment]
@josephdadams Thank you. I have tried that but there is no way to get my code in there somehow.... I might lack privileges to submit changes? (Sorry I am new to github but am an experienced coder)

**Comment by josephdadams** [comment]
#2 

I made it for you

**Comment by bananenbuurman** [comment]
@josephdadams Thank you for your patience with me! Meanwhile I am learning how to do it myself. :)
